name: CI

on:
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  stage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies, style, test and build
        run: |
          npm ci
          npm run style:ci
          npm run test -- --passWithNoTests
          npm run build

      - name: Deploy to S3 staging environment
        uses: jakejarvis/s3-sync-action@v0.5.1
        if: ${{ !startsWith(github.head_ref, 'dependabot') }}
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_STAGING_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "eu-west-1"
          SOURCE_DIR: "build"

      - name: Automatically merge Dependabot PRs
        uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          github-token: ${{ secrets.GH_ACCESS_TOKEN_REPO_SCOPE }}
