name: Auto Merge Dependabot

on:
  pull_request:
    branches:
      - "dependabot/**"

  workflow_dispatch:

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies, lint, test and build
        run: |
          npm install
          npm run lint:ci
          npm run test -- --passWithNoTests
          npm run build

      - name: Automatically merge Dependabot PRs
        uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          github-token: ${{ secrets.GH_ACCESS_TOKEN_REPO_SCOPE }}
